name: Release nightly to Google Play Store

on:
  push:
    paths:
      - "android/**"
      - "assets/**"
      - "lib/**"
      - "pubspec.lock"
      - "pubspec.yaml"
    branches:
      - main
  workflow_dispatch:

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: muxfd/flutter-actions/build-apk@latest
        with:
          keystore-jks: ${{ secrets.UPLOAD_KEYSTORE }}
          store-password: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
          key-password: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}

      - uses: muxfd/flutter-actions/upload-aapk@latest

  aab:
    runs-on: ubuntu-latest
    steps:
      - uses: muxfd/flutter-actions/build-aab@latest
        with:
          keystore-jks: ${{ secrets.UPLOAD_KEYSTORE }}
          store-password: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
          key-password: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}

      - uses: muxfd/flutter-actions/publish-aab@latest
        with:
          service-account-json: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          package-name: com.rtirl.chat
          track: alpha

      - uses: muxfd/flutter-actions/upload-aab@latest
