name: Release nightly to Google Play Store

on:
  push:
    paths:
      - "android/**"
      - "assets/**"
      - "lib/**"
      - "pubspec.lock"
      - "pubspec.yaml"
    branches:
      - main
  workflow_dispatch:

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: muxfd/flutter-build-apk@v1
        with:
          keystore-jks: ${{ secrets.UPLOAD_KEYSTORE }}
          store-password: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
          key-password: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}

      - uses: muxfd/flutter-upload-apk@v1

  aab:
    runs-on: ubuntu-latest
    steps:
      - uses: muxfd/flutter-build-aab@v1
        with:
          keystore-jks: ${{ secrets.UPLOAD_KEYSTORE }}
          store-password: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
          key-password: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}

      - uses: muxfd/flutter-publish-aab@v1
        with:
          service-account-json: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          package-name: com.rtirl.chat
          track: alpha

      - uses: muxfd/flutter-upload-aab@v1
